[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]
all_phone_numbers=501|502|503|504|505|506|507|508|509|510|511|512|612|513|514|516|11880


[from-internal]
exten => 100,1,NoOp(Mock Caller)
 same => n,Playback(demo-congrats)
 same => n,Hangup()

exten => 200,1,NoOp(Mock Callee)
 same => n,Echo()
 same => n,Hangup()



[default]
exten => 007,1,Goto(jamesbond,s,1)
exten => 801,1,Goto(dial-randomcall,s,1)
exten => 802,1,Goto(jukebox,s,1)
exten => 803,1,Goto(feedback,s,1)
exten => 420,1,Goto(420,s,1)
exten => 1312,1,Goto(1312,s,1)
exten => 11880,1,Goto(callcenter,s,1)


; Catch all known emergency numbers to redirect to no-emergency
exten => 110,1,Goto(no-emergency,s,1)
exten => 112,1,Goto(no-emergency,s,1)
exten => 911,1,Goto(no-emergency,s,1)
exten => 999,1,Goto(no-emergency,s,1)

[callcenter-router]

; ----------------- Random call -----------------

[randomcall]
exten => _X.,1,Answer()
 same => n,Playback(/usr/share/asterisk/sounds/randomcall)
 same => n,While($["${DIALSTATUS}" != "ANSWER"])
 same => n,Set(phonenumber=${CUT(all_phone_numbers,|,${RAND(1,${FIELDQTY(all_phone_numbers,|)})})})
 same => n,Dial(Local/${phonenumber}@unet-phones)
 same => n,EndWhile
 same => n,Hangup()


[dial-randomcall]
exten => s,1,Dial(Local/69@randomcall)
 same => n,Hangup()

; ----------------- Jukebox -----------------

[jukebox]
exten =>s,1,Answer()
 same => n,Set(VOLUME(TX)=4)
 same => n,Set(VOLUME(RX)=4)
 same => n,Ringing
 same => n,Wait(2)
 same => n,Set(RANDOM_SOUND_PATH=${SHELL(/usr/local/bin/random_sound.sh)})
 same => n,Playback(${RANDOM_SOUND_PATH})
 same => n,Hangup()

; ----------------- Feedback -----------------
[feedback]
exten =>s,1,Answer()
 same => n,Set(VOLUME(TX)=4)
 same => n,Set(VOLUME(RX)=4)
 same => n,Ringing
 same => n,Wait(2)
 same => n,Playback(/usr/share/asterisk/sounds/feedback)
 ;same => n,Playback(/usr/share/asterisk/sounds/feedback) ;TODO Feedback Ansage
 same => n,Record(/usr/share/asterisk/sounds/feedback/${STRFTIME(,,%Y-%m-%d-%H-%M-%S)}.wav,15,60,k)
 ;same => n,Playback(/usr/share/asterisk/sounds/feedback-thanks)
 same => n,Hangup()

; ----------------- Special numbers -----------------

[420]
exten =>s,1,Answer()
 same => n,Playback(/usr/share/asterisk/sounds/wir-kiffen)
 same => n,Hangup()

[1312]
exten =>s,1,Answer()
 same => n,Playback(/usr/share/asterisk/sounds/polizei)
 same => n,Hangup()

[jamesbond]
exten => s,1,Answer()
same  => n,Playback(james_bond)
same  => n,Hangup()

; ----------------- No emergency -----------------

[no-emergency]
exten =>s,1,Answer()
same => n,Playback(/usr/share/asterisk/sounds/no-emergency)
same =>n,Goto(s,1)


; ----------------- Speeddating -----------------

[speeddating]
exten => s,1,Set(DATEID=${RAND(1,1000000)})
 same => n,Answer()
 same => n,Playback(hello-world) ; TODO: Speeddating user intro
 same => n,Dial(Local/${DATEID}@randomcall,,G(to-date^${DATEID}^1))
 same => n,Hangup()

[to-date]
exten => _X.,1,ConfBridge(${EXTEN})
 same => n,Playback(hello-world) ; TODO: Speeddating user intro
 same => n,Dial(Local/${EXTEN}@hitch,,G(hitch^${EXTEN}^1))
 same => n,Hangup()

[hitch]
exten => _X.,1,Answer()
 same => n,ConfBridge(${EXTEN})
 same => n,Wait(1)
 same => n,Playback(tt-weasels) ; TODO: Questions
 same => n,Wait(10)
 same => n,Hangup()


; ----------------- Callcenter -----------------
[callcenter]
;exten => s,1,Dial(515@unet-phones&516@unet-phones&615@unet-phones&616@unet-phones)
exten => s,1,Dial(PJSIP/anonymous/sip:1@easy17.unet&PJSIP/anonymous/sip:2@easy17.unet&PJSIP/anonymous/sip:1@easy18.unet&PJSIP/anonymous/sip:2@easy18.unet)
 same => n,Hangup()


; ----------------- Outgoing calls -----------------

[unet-phones]
exten => _5XX,1,Dial(PJSIP/anonymous/sip:1@easy${EXTEN:1}.unet)
exten => _6XX,1,Dial(PJSIP/anonymous/sip:2@easy${EXTEN:1}.unet)