[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]
all_phone_numbers=501|502|503|504|505|506|507|508|509|510|511|512|612|513|514|516|11880

; ----------------- Incoming calls -----------------
[default]
; TODO: Originate to LED-ringer here
exten => _X,1,Dial(TAPI/${EXTEN})
 same => n,Goto(handle-${DIALSTATUS},1)

; Forward failed calls to the server for random handling
exten => handle-NOANSWER,1,Dial(Local/s@dial-randomcall@unet-server)
exten => handle-BUSY,1,Dial(Local/s@dial-randomcall@unet-server)
exten => handle-CHANUNAVAIL,1,Dial(Local/s@dial-randomcall@unet-server)
exten => handle-CONGESTION,1,Dial(Local/s@dial-randomcall@unet-server)

; ----------------- Outgoing calls -----------------
[lantiq1]
include => router

[lantiq2]
include => router

[router]
; Allow mesh-internal calls
; If number is in all_phone_numbers → route to unet-phones
; Otherwise → pass to unet-server
exten => _[5-6]XX,1,GotoIf($["${all_phone_numbers}" =~ "${EXTEN}"]?unet-phones,${EXTEN},1:unet-server,${EXTEN},1)

; Route all other numbers to server
exten => _X.,1,Dial(Local/${EXTEN}@unet-server)

[unet-phones]
exten => _5XX,1,Dial(PJSIP/anonymous/sip:1@easy${EXTEN:1}.unet)
exten => _6XX,1,Dial(PJSIP/anonymous/sip:2@easy${EXTEN:1}.unet)

[unet-server]
exten => _X.,1,Dial(PJSIP/anonymous/sip:${EXTEN}@server.unet)
